# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:              Gael Yimen Yimga
email:              yimengael@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is for random thoughts about Life experience,
  Software engineering experience, Personal development
  and Entrepreneurship.
author:             Gael Yimen Yimga
#baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://yimenyimga.com" # the base hostname & protocol for your site, e.g. http://example.com

# Social Profiles
twitter_username:   yimson
github_username:    yimengael
facebook_username:
instagram_username:
linkedin_username: gael-yimen-93819121

# Fields minima uses, but are not defaulted with the jekyll new command.
# Author is the default for posts, the RSS feed, and is used in the footer.
#subtitle: Life, Entrepreneurship, Software engineering
#show_excerpts: true

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-197552345-1 # out your google-analytics code

# New fields not defaulted by Jekyll-new with the minima theme
# Add a copyright. A copyright symbol and year will be added automatically
# copyright: Author Name or Company name
copyright: Gael Yimen Yimga

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
